name: 手动构建 OpenWrt 固件

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 部署环境
        run: |
          curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh | sudo bash
      - name: 克隆仓库
        run: |
          git clone -b openwrt-21.02 --single-branch https://github.com/immortalwrt/immortalwrt
      - name: feeds 相关
        run: |
          cd cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: ssh 连接
        uses: mxschmitt/action-tmate@v3.11
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        timeout-minutes: 180
